name: MLflow Example
permissions:
  id-token: write
  contents: write

on:
  - push

jobs:
  mlflow_example:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MLflow script
      run: |
        python train_model.py
        mlflow ui --host 0.0.0.0 &

    - name: Wait for MLflow UI to start
      run: sleep 10

    - name: Capture MLflow logs
      run: |
        curl -O http://127.0.0.1:5000
        cat index.html

    - name: Stop MLflow UI
      run: pkill -f "mlflow ui"
